# Generated by Django 5.0 on 2024-06-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2_score',
        ),
        migrations.AddField(
            model_name='match',
            name='player1_id',
            field=models.IntegerField(default=0, verbose_name='ID of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(default=0, verbose_name='score of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_id',
            field=models.IntegerField(default=0, verbose_name='ID of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(default=0, verbose_name='score of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of the winner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date of the match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_pong',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_id',
            field=models.IntegerField(default=0, verbose_name='ID of the winner'),
        ),
    ]
