# Generated by Django 5.0 on 2024-04-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
