# Generated by Django 5.0 on 2024-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_pp.jpeg', upload_to='', verbose_name='profile pic'),
        ),
    ]
