# Generated by Django 5.0 on 2024-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='oponent',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='player1_id',
            field=models.IntegerField(default=0, verbose_name='ID of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(default=0, verbose_name='score of player 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_id',
            field=models.IntegerField(default=0, verbose_name='ID of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(default=0, verbose_name='score of player 2'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_id',
            field=models.IntegerField(default=0, verbose_name='ID of the winner'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_name',
            field=models.CharField(default='', max_length=255, verbose_name='Name of the winner'),
        ),
    ]
