# Generated by Django 5.0 on 2024-05-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
