# Generated by Django 5.0 on 2024-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_score_score_morpionparties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpionparties',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of the match'),
        ),
    ]
