# Generated by Django 5.0 on 2024-05-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_student'),
        ('authentication', '0011_alter_morpionparties_date'),
    ]

    operations = [
    ]
