FROM python:3

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/project/

COPY requirements.txt .
COPY wait.sh /tmp

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENTRYPOINT [ "sh", "/tmp/wait.sh" ]

CMD python manage.py makemigrations && \
		python manage.py migrate && \
		python manage.py runserver 0.0.0.0:8000
