FROM python:3

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/project/

EXPOSE 8000

RUN pip install Django==5.0 psycopg==3.1.8 djangorestframework django-cors-headers

CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 