FROM python:3

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/

RUN pip install Django==5.0 psycopg==3.1.8

CMD python project/manage.py makemigrations && python project/manage.py migrate && python project/manage.py runserver 0.0.0.0:8000 